# Generated by Django 3.1.4 on 2020-12-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=800)),
                ('sent_date', models.DateTimeField(verbose_name='date sent')),
            ],
        ),
    ]
